hydra:
    run:
        dir: ./results/${env_name}/${algo_name}/${now:%Y-%m-%d_%H%M%S}_${seed}

# Env config
seed: 42
env_name: walker2d_multi
algo_name: mome
fixed_init_state: True
episode_length: 1000

# MOME parameters
pareto_front_max_length: 50
num_objective_functions: 2

# Initialisation parameters
batch_size: 256
num_evaluations: 1024000
num_init_cvt_samples: 50000 
num_centroids: 128 

# Brax parameters
num_descriptor_dimensions: 2
policy_hidden_layer_sizes: [64, 64] 

# Min and max val of BDs
minval: 0. 
maxval: 1.

# Emitter parameters
iso_sigma: 0.005 
line_sigma: 0.05 
proportion_to_mutate: 0.6 # don't actually use this as purely crossover
eta: 1 
crossover_percentage: 1. 

# Logging parameters
metrics_log_period: 100
plot_repertoire_period: 200
checkpoint_period: 500
save_checkpoint_visualisations: True
save_final_visualisations: True
num_save_visualisations: 10

